Parameters: 
  ClientId:
    Type: String 
    Description: "OAuth2.0 client ID"
    Default: "${self:custom.credentials.clientId}"
    MinLength: 20
  ClientSecret:
    Type: String
    Description: "OAuth2.0 client secret"
    Default: "${self:custom.credentials.clientSecret}"
    MinLength: 40
  GoogleProjectId:
    Type: String
    Description: "Google project identifier"
    Default: "${self:custom.credentials.googleProjectId}"
  GoogleAPIKey:
    Type: String
    Description: "Google API key"
    Default: "${self:custom.credentials.googleApiKey}"
  AlexaSkillId:
    Type: String
    Description: "Alexa skill ID"
    Default: "${self:custom.credentials.alexaSkillId}"
  AlexaClientId:
    Type: String
    Description: "Alexa clinet ID"
    Default: "${self:custom.credentials.alexaClientId}"
  AlexaClientSecret:
    Type: String
    Description: "Alexa client secret"
    Default: "${self:custom.credentials.alexaClientSecret}"
  AlexaEndpoint:
    Type: String
    Description: "Alexa client secret"
    Default: "${self:custom.credentials.alexaEndpoint}"
    AllowedValues: 
      - NorthAmerica
      - Europe
      - FarEast

Conditions: 
  ConnectAlexaLambda: 
    "Fn::Not": [
      {
        "Fn::Equals": [
          "",
          {
            "Ref": "AlexaSkillId"
          }
        ]
      }
    ]
