Parameters: 
  ServerlessDeploymentBucketReplace: 
    Type: String 
    Description: "S3 Deployment Bucket"
    Default: "eliot-cloudformation"
  ClientId:
    Type: String 
    Description: "OAuth2.0 client ID"
    Default: "${self:custom.credentials.clientId}"
    MinLength: 20
    AllowedPattern: ".+"
    ConstraintDescription: "Client ID is required and must have 20 chars"
  ClientSecret:
    Type: String
    Description: "OAuth2.0 client secret"
    Default: "${self:custom.credentials.clientSecret}"
    MinLength: 40
    AllowedPattern: ".+"
    ConstraintDescription: "Client secret is required and must have 40 chars"
  GoogleProjectId:
    Type: String
    Description: "Google project identifier"
    Default: "${self:custom.credentials.googleProjectId}"
  GoogleAPIKey:
    Type: String
    Description: "Google API key"
    Default: "${self:custom.credentials.googleApiKey}"
  AlexaSkillId:
    Type: String
    Description: "Alexa skill ID"
    Default: "${self:custom.credentials.alexaSkillId}"
  AlexaClientId:
    Type: String
    Description: "Alexa clinet ID"
    Default: "${self:custom.credentials.alexaClientId}"
  AlexaClientSecret:
    Type: String
    Description: "Alexa client secret"
    Default: "${self:custom.credentials.alexaClientSecret}"
  AlexaEndpoint:
    Type: String
    Description: "Alexa client secret"
    Default: "${self:custom.credentials.alexaEndpoint}"
    AllowedValues: 
      - NorthAmerica
      - Europe
      - FarEast

Conditions: 
  ConnectAlexaLambda: 
    "Fn::Not": [
      {
        "Fn::Equals": [
          "",
          {
            "Ref": "AlexaSkillId"
          }
        ]
      }
    ]

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "OAuth Credentials"
        Parameters: 
          - ClientId
          - ClientSecret
      - 
        Label: 
          default: "Google Home"
        Parameters: 
          - GoogleProjectId
          - GoogleAPIKey
      - 
        Label: 
          default: "Alexa"
        Parameters: 
          - AlexaSkillId
          - AlexaClientId
          - AlexaClientSecret
          - AlexaEndpoint
      - 
        Label: 
          default: "Infrastructure"
        Parameters: 
          - ServerlessDeploymentBucketReplace
